--!strict

return {
    BlueCrystalEnabled = "Blue Crystal",
    FrostCrystalEnabled = "Frost Crystal",
    MythicalCrystalEnabled = "Mythical Crystal",
    InfernoCrystalEnabled = "Inferno Crystal",
    LegendsCrystalEnabled = "Legends Crystal",
    MuscleEliteCrystalEnabled = "Muscle Elite Crystal",
    GalaxyOracleCrystalEnabled = "Galaxy Oracle Crystal",
    JungleCrystalEnabled = "Jungle Crystal"
}
