--!strict

return {
    {
        Name = "Secret",
        Description = "Teleport to Secret area",
        CFrame = CFrame.new(1953.5679, -2.0883, 6186.9780)
    },
    {
        Name = "Muscle King",
        Description = "Teleport to Muscle King",
        CFrame = CFrame.new(-8745.49, 20, -5853.26)
    },
    {
        Name = "Jungle GYM",
        Description = "Teleport to Jungle gym",
        CFrame = CFrame.new(-8383.83, 6.81, 2390.31)
    },
    {
        Name = "Jungle Barlift",
        Description = "Go to the jungle barlift",
        CFrame = CFrame.new(-8659.50, 6.81, 2091.25)
    },
    {
        Name = "Legends GYM",
        Description = "Teleport to Legends gym",
        CFrame = CFrame.new(4270.22, 991.53, -3840.61)
    },
    {
        Name = "Eternal GYM",
        Description = "Teleport to Eternal gym",
        CFrame = CFrame.new(-6876.60, 7.38, -1280.12)
    },
    {
        Name = "Mystic GYM",
        Description = "Teleport to Mystic gym",
        CFrame = CFrame.new(2333.94, 7.38, 1068.95)
    },
    {
        Name = "Frost GYM",
        Description = "Teleport to Frost gym",
        CFrame = CFrame.new(-2648.81, 7.38, -427.46)
    },
    {
        Name = "Tiny Island",
        Description = "Teleport to tiny island (safe zone)",
        CFrame = CFrame.new(8.54, 7.53, 1999.76)
    }
}
